apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2016-01-19T09:51:30Z
  labels:
    app: centos
  name: openshift-qpid
  namespace: pulp
  resourceVersion: "25602"
  selfLink: /oapi/v1/namespaces/pulp/deploymentconfigs/openshift-qpid
  uid: 373e774b-be92-11e5-a8c8-080027c5bfa9
spec:
  replicas: 1
  selector:
    app: centos
    deploymentconfig: openshift-qpid
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: centos
        deploymentconfig: openshift-qpid
    spec:
      containers:
      - image: 172.30.236.154:5000/pulp/openshift-qpid@sha256:f622693315debd54d219aa1c8918bb8c031f4106312e92c394d5ab45f26d0725
        imagePullPolicy: Always
        name: openshift-qpid
        ports:
        - containerPort: 5672
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - openshift-qpid
      from:
        kind: ImageStreamTag
        name: openshift-qpid:latest
      lastTriggeredImage: 172.30.236.154:5000/pulp/openshift-qpid@sha256:f622693315debd54d219aa1c8918bb8c031f4106312e92c394d5ab45f26d0725
    type: ImageChange
status:
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: 172.30.236.154:5000/pulp/openshift-qpid:latest
      type: ImageChange
  latestVersion: 1
